package packet

var PenaltiesById = map[uint8]string{
	0:  "Drive through",
	1:  "Stop Go",
	2:  "Grid penalty",
	3:  "Penalty reminder",
	4:  "Time penalty",
	5:  "Warning",
	6:  "Disqualified",
	7:  "Removed from formation lap",
	8:  "Parked too long timer",
	9:  "Tyre regulations",
	10: "This lap invalidated",
	11: "This and next lap invalidated",
	12: "This lap invalidated without reason",
	13: "This and next lap invalidated without reason",
	14: "This and previous lap invalidated",
	15: "This and previous lap invalidated without reason",
	16: "Retired",
	17: "Black flag timer",
}

var InfringementsById = map[uint8]string{
	0:  "Blocking by slow driving",
	1:  "Blocking by wrong way driving",
	2:  "Reversing off the start line",
	3:  "Big Collision",
	4:  "Small Collision",
	5:  "Collision failed to hand back position single",
	6:  "Collision failed to hand back position multiple",
	7:  "Corner cutting gained time",
	8:  "Corner cutting overtake single",
	9:  "Corner cutting overtake multiple",
	10: "Crossed pit exit lane",
	11: "Ignoring blue flags",
	12: "Ignoring yellow flags",
	13: "Ignoring drive through",
	14: "Too many drive throughs",
	15: "Drive through reminder serve within n laps",
	16: "Drive through reminder serve this lap",
	17: "Pit lane speeding",
	18: "Parked for too long",
	19: "Ignoring tyre regulations",
	20: "Too many penalties",
	21: "Multiple warnings",
	22: "Approaching disqualification",
	23: "Tyre regulations select single",
	24: "Tyre regulations select multiple",
	25: "SetLap invalidated corner cutting",
	26: "SetLap invalidated running wide",
	27: "Corner cutting ran wide gained time minor",
	28: "Corner cutting ran wide gained time significant",
	29: "Corner cutting ran wide gained time extreme",
	30: "SetLap invalidated wall riding",
	31: "SetLap invalidated flashback used",
	32: "SetLap invalidated reset to track",
	33: "Blocking the pitlane",
	34: "Jump start",
	35: "Safety car to car collision",
	36: "Safety car illegal overtake",
	37: "Safety car exceeding allowed pace",
	38: "Virtual safety car exceeding allowed pace",
	39: "Formation lap below allowed speed",
	40: "Retired mechanical failure",
	41: "Retired terminally damaged",
	42: "Safety car falling too far back",
	43: "Black flag timer",
	44: "Unserved stop go penalty",
	45: "Unserved drive through penalty",
	46: "Engine component change",
	47: "Gearbox change",
	48: "League grid penalty",
	49: "Retry penalty",
	50: "Illegal time gain",
	51: "Mandatory pitstop",
}
